# Generated by Django 3.2.8 on 2021-12-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
