# Generated by Django 3.2.8 on 2021-12-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0005_delete_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='postal',
            field=models.CharField(default='', max_length=50, verbose_name='Postal/Zip'),
        ),
        migrations.AddField(
            model_name='location',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_home.profile'),
        ),
    ]
