# Generated by Django 3.2.8 on 2021-12-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0007_location_add_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='place',
        ),
    ]
